import React, { Component } from 'react'
import { render } from 'react-dom'
import Header from '../../Layout/Header/Header'
import Footer from '../../Layout/Footer/Footer'
import css from './privacy.scss'

export default class Privacy extends Component {
  render() {
    return(
      <div>
        <Header />
        <div className='container'>
          <a href='/en'><i className='fa fa-long-arrow-left'></i> Back</a>
          <h1>Privacy</h1>

          <p>
            Milieu Technologies Ltd. and its affiliates (“Milieu”, “we” or “us”) are committed to protecting the privacy of all individuals who:
          </p>

          <ul>
            <li>register with or visit any websites or mobile sites offered by Milieu, including without limitation milieu.io and including all subdomains thereof, present and future (the “Website”);</li>
            <li>respond to any Milieu survey (the “Surveys”);</li>
            <li>register with or use the mobile applications that Milieu makes available from time to time (the "Applications");</li>
            <li>register with or use the Services using _______, _______, _______ and other Milieu products and services (the "Platforms");</li>
            <li>post information, material, or commentary via our Websites, Surveys, Applications, Platforms, or other Milieu or third-party publicly accessible online sites (the “Uploads”); and</li>
            <li>are or have registered with us to receive information, including marketing information, newsletters, or any other information, on the Websites, or with a Milieu representative by email, at an event, web seminar, or other in-person meeting (the “Mailing List”).</li>
          </ul>

          <p>
            To make this policy easier to read, we call the Website, the Surveys, the Applications, the Platforms, the Uploads, and the Mailing List together, the "Services". When we talk about “Personal Information”, we mean information relating to you or other identifiable individuals, and which may include but is not limited to your name, mailing address, telephone number, e-mail address, business facsimile number, and credit card information. Personal Information, however, does not include certain business contact information used for the purpose of communicating or facilitating communication with you, as an individual, in relation to your employment, business or profession.
          </p>

          <p>
            It is Milieu’s policy to respect your privacy and the privacy of all users of the Services. This Privacy Policy has been established to help you understand our commitment to protecting your privacy and personal data, and the steps we take to ensure it. By continuing to visit and/or use any of the Services, you agree to be bound by the terms of the present Privacy Policy (the “Privacy Policy”).
          </p>

          <p>
            Milieu reserves the right, at any time, to modify or replace the Privacy Policy. The most recent version of the Privacy Policy is available at Milieu.io/legal/privacy. Please check the Privacy Policy periodically for changes, though we will also notify you via email or other direct electronic communication method of any changes that, in our sole discretion, materially impact your use of the Services or the treatment of your Personal Information. Your use of the Services following the posting of any changes to the Privacy Policy constitutes acceptance of those changes.
          </p>

          <h2>
            Personal Information Collected by Milieu
          </h2>

          <p>
            We will always collect your Personal Information by fair and lawful means (for example, when you purchase a report on our web site; register to receive general information or marketing information such as our newsletter or product information; or attend an event or web seminar). We may collect Personal Information from you directly and/or from third parties where we have obtained your consent to do so or as otherwise required or permitted by law.
          </p>

          <p>
            Personal Information that we collect may include:
          </p>

          <ul>
            <li>your full name, username, email address, and other contact details</li>
            <li>the geographic area and/or postal code and/or other indicator of location where you use your computer and mobile devices</li>
            <li>your IP Address and, when applicable, timestamp information related to your consent and confirmation of consent</li>
            <li>other information submitted by you or your organizational representatives via various methods (phone, email, online forms, surveys, in-person meetings, etc.)</li>
            <li>your billing address and any necessary other information to complete any financial transaction, and when making purchases through the Services, we may also collect your credit card or PayPal information</li>
            <li>content generated by you and communicated to us via the Services (such as messages, posts, comments, pages, profiles, images, feeds or communications exchanged on the Services)</li>
            <li>information we may receive relating to communications you send us, such as queries or comments concerning our Services</li>
          </ul>

          <p>
            We generally obtain your consent prior to collecting, and in any case, prior to using or disclosing your Personal Information for any purpose. You may provide your consent to us either orally, electronically or in writing. In some cases, your consent may be implied based on our existing business relationship or when your conduct provides a reasonable basis for a belief that consent has been given.
          </p>

          <h2>
            Purposes and Uses of Personal Information
          </h2>

          <p>
            We will generally identify the purposes for which we use your Personal Information at the time we collect such information from you and obtain your consent, in any case, prior to such use. We may use your Personal Information for the following purposes (the “Purposes”):
          </p>

          <ul>
            <li>to build reports, including but not limited to aggregated location-based sentiment analyses, based on engagement and other types of surveys as well as other publicly available information;</li>
            <li>to register you for, and facilitate your participation in, certain areas of the Websites or other aspects of the Services;</li>
            <li>to respond to your inquiries;</li>
            <li>to process product orders, to deliver products and to satisfy on-going service requirements;</li>
            <li>to respond to product or service complaints, product/service claims or product/service information requests;</li>
            <li>to collect your Personal Information in aggregate form to develop sentiment analyses or other reports, as well as to perform sales analysis and identify marketing opportunities and strategies;</li>
            <li>to advise you about new products and services that may be of interest to you;</li>
            <li>to collect opinions and comments in regard to Milieu’ operations;</li>
            <li>to include you on Milieu’ mailing list(s) and/or to send you newsletters, marketing information, or other information relating to Milieu’ products and services;</li>
            <li>to recruit for positions at Milieu and, when applicable, to process your application for employment and resume;</li>
            <li>to administer our website;</li>
            <li>to investigate legal claims;</li>
            <li>such purposes for which Milieu may obtain consent from time to time; and</li>
            <li>such other uses as may be permitted or required by applicable law.</li>
          </ul>

          <h2>
            Disclosure of Information
          </h2>

          <p>
            We may transfer your Personal Information to third party service providers with whom we have a contractual agreement that includes appropriate privacy, confidentiality or security standards, where such third parties are assisting us with the Purposes – such as service providers that provide marketing services, billing or payment support, telephone support, or data storage or processing.
          </p>

          <p>
            Generally, we will only make disclosures of Personal Information to such persons for which you provide your consent. Notwithstanding the foregoing, we may also make disclosures of Personal Information to a potential acquirer in connection with a transaction involving the sale of some or all of the business of Milieu (in which case the use of your personal information by the new entity would continue to be limited by applicable law), or as otherwise permitted or required by law.
          </p>

          <p>
            Notwithstanding anything in the Privacy Policy to the contrary, we may share any information we have collected about you:
          </p>

          <ol>
            <li>When you explicitly consent to the disclosure of such information.</li>
            <li>Where we are legally required to do so, such as in response to court orders or legal process, or to establish, protect, or exercise our legal rights or to defend against legal claims or demands.</li>
            <li>If we believe it is necessary in order to investigate, prevent, or take action regarding illegal activities, fraud, or situations involving potential threats to the rights, property, or personal safety of any person, or other exigent circumstances.</li>
            <li>If we believe it is necessary to investigate, prevent, or take action regarding situations that involve abuse of the Services infrastructure or the Internet in general (such as voluminous spamming, denial of service attacks, or attempts to compromise the security of the Website infrastructure or the Services generally), or to otherwise protect our assets or rights.</li>
            <li>To a parent company, subsidiaries, joint ventures, or other companies controlling, controlled by, or under common control with Milieu.</li>
            <li>If we are acquired by or merged with another entity (in which case we will require such entity to assume our obligations under this Privacy Policy or inform you that you are covered by a new privacy policy complying with Canadian law); and</li>
            <li>If information has been made public, is aggregated, or is otherwise non-Personal Information or if it has been anonymized.</li>
          </ol>

          <p>
            Subject to obligations consistent with this Privacy Policy, we may also disclose information to our affiliates, agents, contractors, and service providers in order to facilitate the functioning of the Services or to perform tasks that are integral to the Services, such as processing transactions, fulfilling requests for information, or providing support services or other tasks, from time to time.
          </p>

          <p>
            In addition, we may send Personal Information outside of Canada or the province in which you reside for the Purposes, including for processing and storage by service providers in connection with such Purposes. However, you should note that to the extent that any Personal Information is out of the country or the province, it is subject to the laws of the country in which it is held, and may be subject to disclosure to the governments, courts or law enforcement or regulatory agencies of such other country, pursuant to the laws of such country.
          </p>

          <h2>
            Safeguards, Accuracy, and Compliance
          </h2>

          <p>
            We have implemented reasonable physical, organizational, contractual and technological security measures to protect your Personal Information from loss or theft, unauthorized access, disclosure, copying, use or modification. The only Milieu representatives who are granted access to your Personal Information are those with a business ‘need-to-know’ or whose duties reasonably require such information. No transmission over the Internet or electronic storage can be guaranteed completely.  As a result, while we strive to protect personal information we make no warranty or guarantee.
          </p>

          <p>
            You can help protect the security of your personal information.  Milieu requires as a condition of the use of the Services that you keep your passwords secure and do not share the use of your account with other individuals. Should we become aware of a breach of our security involving your personal information, we will take reasonable steps to notify you in a timely manner and shall comply with all other legal requirements.
          </p>

          <p>
            We will keep the Personal Information that we collect at the Milieu offices or at the offices of our third party service providers, as applicable and as permitted. We may keep a record of your Personal Information, correspondence or comments, in a file specific to you. We will utilize, disclose or retain your Personal Information for as long as necessary to fulfill the purposes for which that Personal Information was collected and as permitted or required by law.
          </p>

          <p>
            If you make a written request to review any Personal Information about you that we have collected, utilized or disclosed, we will provide you with any such Personal Information to the extent permitted by law. We assume that your Personal Information provided by you is accurate, complete and up-to-date. While we will not routinely update your Personal Information, unless such a process is necessary, you may request access to your information at any time and notify us if you discover that the information is not correct. We expect you, from time to time, to supply us with written updates to your Personal Information, when required.
          </p>

          <p>
            At any time, you can challenge the accuracy or completeness of your Personal Information in our records. If you successfully demonstrate that your Personal Information in our records is inaccurate or incomplete, we will amend the Personal Information as required. We will not charge any costs for you to access your Personal Information in our records or to access our privacy practices without first providing you with an estimate of the approximate costs, if any. We may request that you provide sufficient identification to permit access to your Personal Information. Any such identifying information shall be used only for this purpose.
          </p>

          <h2>
            Email preferences
          </h2>

          <p>
            You may opt out of marketing communications sent by Milieu by following the unsubscribe instructions included in each marketing email or by contacting us via email.
          </p>

          <h2>Children</h2>

          <p>
            Our services are directed to technology professionals and not intended for children 13 or under.
          </p>

          <h2>
            Cookies
          </h2>

          <p>
            A cookie is a small text file placed on a personal computer as a person visits a website.  We associate a cookie with information that identifies you if you are a registered user of our websites.  We may use the resulting information in the ways described below.  We may also use cookies and associated web beacons to improve and customize your experience with the Services, to help us recognize you across the Services, as well as to measure, analyze, and improve the use of the Services, as well as the effectiveness of our email campaigns.
          </p>

          <p>
            Our server logs collect information about visits and system capabilities as you access and use the Services. We do not routinely associate such data with your profile except for investigative purposes as specifically described below. You may disable or block any cookies (and so, any associated web beacons) by using the tools available in most browsers.
          </p>

          <p>
            If you are registering for our websites, you may choose whether to activate automatic recognition of your computer based on the placement of a persistent cookie that identifies your computer.  If you choose not to accept that persistent cookie, or to delete it at any time, you may be asked to re-enter your log on credentials each time you access the website and or other information affecting your use of the Websites, for example, language and location.
          </p>

          <h2>
            Contacting Milieu’s Privacy Officer
          </h2>

          <p>
            All comments, questions, concerns or complaints regarding your Personal Information, this Privacy Statement or our privacy practices, should be forwarded to our Privacy Officer as follows.
          </p>

          <p>
            E-mail: info@milieu.io
          </p>

          <p>
            Privacy Officer <br/>
            29 Melgund Ave., Apt 1 <br/>
            Ottawa, Ontario <br/>
            Canada
          </p>
        </div>
        <Footer />
      </div>
    );
  }
}

document.addEventListener('turbolinks:load', () => {
  const privacy = document.querySelector('#privacy')
  privacy && render(<Privacy/>, privacy)
})
